/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/request': typeof RequestRoute
  '/topics': typeof TopicsRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/request': typeof RequestRoute
  '/topics': typeof TopicsRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/request': typeof RequestRoute
  '/topics': typeof TopicsRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/request'
    | '/topics'
    | '/articles/$slug'
    | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/request'
    | '/topics'
    | '/articles/$slug'
    | '/topics/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/request'
    | '/topics'
    | '/articles/$slug'
    | '/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RequestRoute: typeof RequestRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RequestRoute: RequestRoute,
  TopicsRoute: TopicsRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
